apiVersion: apps/v1
kind: Deployment
metadata:
  name: cute-animals-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cute-animals-hub
  template:
    metadata:
      labels:
        app: cute-animals-hub
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.port } }
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbUrl
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbUser
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbPassword
