apiVersion: batch/v1
kind: Job
metadata:
  name: flyway-migrate
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: "{{ .Values.flyway.image }}"
          command: [ "flyway", "-locations={{ .Values.flyway.locations }}", "-connectRetries=60", "migrate" ]
          volumeMounts:
            - name: flyway-scripts
              mountPath: /flyway/sql
          env:
            - name: FLYWAY_URL
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbUrl
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbUser
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cute-animals-secret
                  key: dbPassword
      restartPolicy: Never
      volumes:
        - name: flyway-scripts
          configMap:
            name: flyway-sql-scripts
  backoffLimit: 2
